### ISSUE TITLE
how to run tauri app on windows?

### ISSUE THREAD

**Issue by bukowa** [bukowa/tauri-e2e#2]
On linux we use `xvfb` what should be used on Windows?

**Comment by bukowa** [comment]
It "just works", maybe someone can explain why?
https://github.com/bukowa/tauri-e2e/actions/runs/9724666727/job/26841130377

**Comment by lucasfernog** [comment]
i'm trying to make webdriver work on GitHub Actions on tauri-driver but seems like not even your solution is working anymore :(

```
Built application at: D:\a\tauri-e2e\tauri-e2e\target\release\tauri-app.exe
just selenium::test
just javascript::test
npm install
up to date, audited 113 packages in 820ms
24 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm run build
> @tauri-e2e/selenium@0.2.2 build
> tsc
just examples::run
just selenium__javascript::build
npm install
up to date, audited 113 packages in 931ms
24 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm run build
> @tauri-e2e/selenium@0.2.2 build
> tsc
node ./quick-start.js
Using remote WebDriver from env { SELENIUM_REMOTE_URL: 'http://127.0.0.1:4674/' }
Ignoring error {
  error: Error: kill EPERM
      at process.kill (node:internal/process/per_thread:223:13)
      at killWebDriver (file:///D:/a/tauri-e2e/tauri-e2e/selenium/javascript/dist/launch/spawn.js:195:25)
      at process.<anonymous> (file:///D:/a/tauri-e2e/tauri-e2e/selenium/javascript/dist/launch/spawn.js:155:13)
      at process.emit (node:events:532:35)
      at process._fatalException (node:internal/process/execution:198:19)
      at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:115:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    errno: -4048,
    code: 'EPERM',
    syscall: 'kill'
  }
}
Setting log level for WebDriver { logLevel: 'DEBUG' }
Spawning WebDriver {
  path: 'D:\\a\\tauri-e2e\\tauri-e2e\\selenium\\javascript\\examples\\node_modules\\.cache\\@tauri-e2e\\selenium\\edgedriver\\msedgedriver.136.0.3240.50.exe',
  args: [ '--host=127.0.0.1', '--port=4674', '--logc-level=DEBUG' ],
  spawnOpts: { stdio: [ null, 'pipe', 'pipe' ], detached: false }
}
Setting up exit handlers
Creating new Builder.
Using remote server address. { url: 'http://127.0.0.1:4674/' }
Using binary path. { binary: '../../../target/release/tauri-app.exe' }
Using capabilities. {
  capabilities: Capabilities {
    map_: Map(2) {
      'browserName' => 'webview2',
      'ms:edgeOptions' => [Object]
    }
  }
}
Starting Microsoft Edge WebDriver 136.0.3240.50 (4e2c41645f24197463afa2ab6aa999352ee8255c) on port 4674
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
Process event received { event: 'uncaughtExceptionMonitor' }
Killing WebDriver process { pid: 1128, signal: 'SIGTERM' }
WebDriver process killed (probably) { exitCode: null }
Process event received { event: 'exit' }
Killing WebDriver process { pid: 1128, signal: 'SIGTERM' }
WebDriver process killed (probably) { exitCode: null }
D:\a\tauri-e2e\tauri-e2e\node_modules\selenium-webdriver\http\index.js:293
      onError(new Error(message))
              ^
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4674
    at ClientRequest.<anonymous> (D:\a\tauri-e2e\tauri-e2e\node_modules\selenium-webdriver\http\index.js:293:15)
    at ClientRequest.emit (node:events:520:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v22.2.0
error: Recipe `_run` failed on line 20 with exit code 1
error: Recipe `test` failed on line 5 with exit code 1
error: Recipe `test` failed on line 4 with exit code 1
error: Recipe `test` failed on line 17 with exit code 1
```

**Comment by bukowa** [comment]
Not sure what's going on here

**Comment by lucasfernog** [comment]
i managed to fix my problems with https://github.com/tauri-apps/webdriver-example/pull/19
